# Generated by Django 4.1.4 on 2023-01-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogmodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='upload_to',
        ),
    ]
