# Generated by Django 4.1.4 on 2023-01-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogmodel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='upload_to',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
