# Generated by Django 4.1.4 on 2023-01-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogmodel_options_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='product',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
