# Generated by Django 4.1.4 on 2023-01-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogmodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='field_name',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
