# Generated by Django 4.1.4 on 2023-01-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogmodel_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='link',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
