# Generated by Django 4.1.4 on 2023-01-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogmodel_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='field_name',
        ),
    ]
